swagger: "2.0"
info:
  description: "The trace analysis server protocol is used between a trace viewer (client) and a trace analysis library (the à server) to show high level analysis of a trace like the disks I/O activity, the CPU usage, the callstack, etc."
  version: "1.0.0"
  title: "Trace analysis server protocol specifications"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
tags:
- name: "Traces"
  description: "Handle and manage traces"
- name: "Projects"
  description: "Handle and manage projects"
- name: "Timeline"
  description: "Query for timeline models"
- name: "XY"
  description: "Query for xy models"
schemes:
- "http"
paths:
  /traces:
    get:
      tags:
      - "Traces"
      summary: "Get the list of traces available on the server"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      responses:
    post:
      tags:
      - "Traces"
      summary: "Upload a trace to the server"
      description: ""
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: ""
        required: true
  /traces/{traceID}:
    get:
      tags:
      - "Traces"
      summary: "Get informations about a specific trace on the server"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: traceID
        in: path
        description: ""
        required: true
        type: "string"
      responses:
        200:
          description: "successful operation"
    delete:
      tags:
      - "Traces"
      summary: "Remove a trace from the server"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: traceID
        in: path
        description: ""
        required: true
        type: "string"